name: expense_manager_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  readmore: ^3.0.0
  pie_chart: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/expense_splash_image.svg
    - assets/down_arrow.svg
    - assets/Medicine.svg
    - assets/food.svg
    - assets/fuel.svg
    - assets/photo.svg
