name: sumiti_darpan_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: 0.19.0 
  readmore: ^3.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.2
  shared_preferences: ^2.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dummy.jpg
    - assets/profile_image.png
    - assets/samiti_logo.png
    - assets/gallery.png
    - assets/camera.jpg
    
